#!/usr/bin/env bash
# Shippable `libkeryx-llama-vk.so` — the miner's in-process llama.cpp engine, AMD/Vulkan flavor
# (zero-dup: hosts the model for the PoM walk + serves OPoI inference on the same resident VRAM).
# Built inside the `llama-vk-toolchain` image (ubuntu-20.04 → glibc ≤ 2.31; cmake + glslc +
# Vulkan-Headers overlaid — the same toolchain that builds the bundled Vulkan llama-server).
#
# llama.cpp PINNED to b10015 — the SAME pin as build-keryx-llama.sh (CUDA flavor) and
# build-llama-server.sh. Bump all together, then re-verify the byte gate / spike.
#
# The keryx_vk_* exports (tools/keryx-llama/keryx_vk_exports.inc.cpp) are APPENDED to
# ggml-vulkan.cpp before building — every referenced symbol is file-scope static there, so the
# append is pin-robust (no line-anchored patch).
#
# Usage: build-keryx-llama-vk.sh [JOBS]
# Output: hiveos/dist-amd/libkeryx-llama-vk.so  (package-amd.sh bundles it when present)
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
JOBS="${1:-$(nproc)}"
TAG=b10015
OUT="$REPO/hiveos/dist-amd"
mkdir -p "$OUT"
SRC=/tmp/llama-src-$TAG-vk
if [ ! -d "$SRC" ]; then
  git clone --quiet --depth 1 --branch "$TAG" https://github.com/ggml-org/llama.cpp "$SRC"
fi

# Refresh the appended keryx exports every run: strip everything from the marker down, then
# re-append the current snippet — so snippet edits always land (a presence-grep guard would skip
# them once the first append exists).
GV="$SRC/ggml/src/ggml-vulkan/ggml-vulkan.cpp"
MARK='// ── KERYX-EXPORTS-APPEND (everything below is re-generated by build-keryx-llama-vk.sh)'
if grep -qF "$MARK" "$GV"; then
  sed -i "/$(printf '%s' "$MARK" | sed 's/[[\.*^$/]/\\&/g')/,\$d" "$GV"
fi
{ printf '%s\n' "$MARK"; cat "$REPO/tools/keryx-llama/keryx_vk_exports.inc.cpp"; } >> "$GV"

mkdir -p /tmp/kvk-build-cache
docker run --rm \
  -v "$SRC":/llama -v "$REPO":/repo:ro -v "$OUT":/out \
  -v /tmp/kvk-build-cache:/tmp/kvk-build \
  -e JOBS="$JOBS" -e KERYX_SPIKE="${KERYX_SPIKE:-0}" \
  llama-vk-toolchain bash -euo pipefail -c '
    B=/tmp/kvk-build
    cmake -S /llama -B $B \
      -DGGML_VULKAN=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
      -DLLAMA_CURL=OFF -DGGML_NATIVE=OFF \
      -DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_EXAMPLES=OFF -DLLAMA_BUILD_TOOLS=OFF \
      -DCMAKE_BUILD_TYPE=Release
    cmake --build $B --target llama -j "$JOBS"

    # Our walk/fetch shaders -> SPIR-V as C initializer lists the wrapper #includes.
    G=/tmp/kvk-gen && mkdir -p $G
    glslc --target-env=vulkan1.2 -O -mfmt=c -o $G/pom_walk_vk.spv.inc  /repo/tools/keryx-llama/pom_walk_vk.comp
    glslc --target-env=vulkan1.2 -O -mfmt=c -o $G/pom_fetch_vk.spv.inc /repo/tools/keryx-llama/pom_fetch_vk.comp

    g++ -O2 -std=c++17 -shared -fPIC -fopenmp /repo/tools/keryx-llama/keryx_llama_vk.cpp \
      -I $G -I /llama/include -I /llama/ggml/include -I /llama/src -I /llama/common \
      -Wl,--start-group \
        $B/src/libllama.a \
        $B/ggml/src/ggml-vulkan/libggml-vulkan.a \
        $B/ggml/src/libggml-cpu.a $B/ggml/src/libggml.a $B/ggml/src/libggml-base.a \
      -Wl,--end-group \
      -lvulkan -lpthread -ldl -o /out/libkeryx-llama-vk.so
    chmod a+rx /out/libkeryx-llama-vk.so

    # Byte-identity spike (KERYX_SPIKE=1): links the .so itself (one llama/ggml per process).
    if [ "${KERYX_SPIKE:-0}" = "1" ]; then
      g++ -O2 -std=c++17 /repo/tools/keryx-llama/spike_vk.cpp \
        -I /llama/include -I /llama/ggml/include \
        -L /out -l:libkeryx-llama-vk.so -Wl,-rpath,"\$ORIGIN" \
        -o /out/spike_vk
      chmod a+rx /out/spike_vk
    fi
  '
echo ">> libkeryx-llama-vk.so: $(ls -la "$OUT/libkeryx-llama-vk.so" | awk '{print $5}') bytes, glibc=$(objdump -T "$OUT/libkeryx-llama-vk.so" 2>/dev/null | grep -oE 'GLIBC_[0-9.]+' | sort -V | tail -1), syms=$(nm -D "$OUT/libkeryx-llama-vk.so" | grep -c keryx_llama)"
