#!/usr/bin/env bash
# Shippable `libkeryx-llama-vk.so` — the miner's in-process llama.cpp engine, AMD/Vulkan flavor
# (zero-dup: hosts the model for the PoM walk + serves OPoI inference on the same resident VRAM).
# Built inside the `llama-vk-toolchain` image (ubuntu-20.04 → glibc ≤ 2.31; cmake + glslc +
# Vulkan-Headers overlaid — the same toolchain that builds the bundled Vulkan llama-server).
#
# llama.cpp PINNED to b10015 — the SAME pin as build-keryx-llama.sh (CUDA flavor) and
# build-llama-server.sh. Bump all together, then re-verify the byte gate / spike.
#
# The keryx_vk_* exports (tools/keryx-llama/keryx_vk_exports.inc.cpp) are APPENDED to
# ggml-vulkan.cpp before building — every referenced symbol is file-scope static there, so the
# append is pin-robust (no line-anchored patch).
#
# Usage: build-keryx-llama-vk.sh [JOBS] [noavx]
# Output: hiveos/dist-amd/libkeryx-llama-vk.so  (package-amd.sh bundles it when present)
#
# "noavx" 2nd arg: baseline-ISA CPU backend (GGML_AVX/AVX2/FMA/F16C/BMI2 OFF, SSE4.2 kept) →
# hiveos/dist-amd/libkeryx-llama-vk-noavx.so. The default build bakes AVX2-level SIMD into the
# ggml CPU path with NO runtime dispatch — pre-AVX rig CPUs SIGILL on it (v0.7.2 fix); the
# miner auto-selects the -vk-noavx file on such CPUs.
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
JOBS="${1:-$(nproc)}"
VARIANT="${2:-avx}"
TAG=b10015
case "$VARIANT" in
  avx)   OUTNAME=libkeryx-llama-vk.so;       SIMD_FLAGS=""; BCACHE=/tmp/kvk-build-cache ;;
  noavx) OUTNAME=libkeryx-llama-vk-noavx.so; SIMD_FLAGS="-DGGML_AVX=OFF -DGGML_AVX2=OFF -DGGML_FMA=OFF -DGGML_F16C=OFF -DGGML_BMI2=OFF -DGGML_AVX_VNNI=OFF"; BCACHE=/tmp/kvk-build-cache-noavx ;;
  *) echo "usage: $0 [JOBS] [noavx]"; exit 1 ;;
esac
OUT="$REPO/hiveos/dist-amd"
mkdir -p "$OUT"
SRC=/tmp/llama-src-$TAG-vk
if [ ! -d "$SRC" ]; then
  git clone --quiet --depth 1 --branch "$TAG" https://github.com/ggml-org/llama.cpp "$SRC"
fi

# Refresh the appended keryx exports every run: strip everything from the marker down, then
# re-append the current snippet — so snippet edits always land (a presence-grep guard would skip
# them once the first append exists).
GV="$SRC/ggml/src/ggml-vulkan/ggml-vulkan.cpp"
MARK='// ── KERYX-EXPORTS-APPEND (everything below is re-generated by build-keryx-llama-vk.sh)'
if grep -qF "$MARK" "$GV"; then
  sed -i "/$(printf '%s' "$MARK" | sed 's/[[\.*^$/]/\\&/g')/,\$d" "$GV"
fi
{ printf '%s\n' "$MARK"; cat "$REPO/tools/keryx-llama/keryx_vk_exports.inc.cpp"; } >> "$GV"

mkdir -p "$BCACHE"
docker run --rm \
  -v "$SRC":/llama -v "$REPO":/repo:ro -v "$OUT":/out \
  -v "$BCACHE":/tmp/kvk-build \
  -e JOBS="$JOBS" -e KERYX_SPIKE="${KERYX_SPIKE:-0}" -e SIMD_FLAGS="$SIMD_FLAGS" -e OUTNAME="$OUTNAME" \
  llama-vk-toolchain bash -euo pipefail -c '
    B=/tmp/kvk-build
    cmake -S /llama -B $B \
      -DGGML_VULKAN=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
      -DLLAMA_CURL=OFF -DGGML_NATIVE=OFF $SIMD_FLAGS \
      -DLLAMA_BUILD_TESTS=OFF -DLLAMA_BUILD_EXAMPLES=OFF -DLLAMA_BUILD_TOOLS=OFF \
      -DCMAKE_BUILD_TYPE=Release
    cmake --build $B --target llama -j "$JOBS"

    # Our walk/fetch shaders -> SPIR-V as C initializer lists the wrapper #includes.
    G=/tmp/kvk-gen && mkdir -p $G
    glslc --target-env=vulkan1.2 -O -mfmt=c -o $G/pom_walk_vk.spv.inc  /repo/tools/keryx-llama/pom_walk_vk.comp
    glslc --target-env=vulkan1.2 -O -mfmt=c -o $G/pom_fetch_vk.spv.inc /repo/tools/keryx-llama/pom_fetch_vk.comp

    g++ -O2 -std=c++17 -shared -fPIC -fopenmp /repo/tools/keryx-llama/keryx_llama_vk.cpp \
      -I $G -I /llama/include -I /llama/ggml/include -I /llama/src -I /llama/common \
      -Wl,--start-group \
        $B/src/libllama.a \
        $B/ggml/src/ggml-vulkan/libggml-vulkan.a \
        $B/ggml/src/libggml-cpu.a $B/ggml/src/libggml.a $B/ggml/src/libggml-base.a \
      -Wl,--end-group \
      -lvulkan -lpthread -ldl -o /out/$OUTNAME
    chmod a+rx /out/$OUTNAME

    # Byte-identity spike (KERYX_SPIKE=1): links the .so itself (one llama/ggml per process).
    if [ "${KERYX_SPIKE:-0}" = "1" ]; then
      g++ -O2 -std=c++17 /repo/tools/keryx-llama/spike_vk.cpp \
        -I /llama/include -I /llama/ggml/include \
        -L /out -l:libkeryx-llama-vk.so -Wl,-rpath,"\$ORIGIN" \
        -o /out/spike_vk
      chmod a+rx /out/spike_vk
    fi
  '
echo ">> $OUTNAME: $(ls -la "$OUT/$OUTNAME" | awk '{print $5}') bytes, glibc=$(objdump -T "$OUT/$OUTNAME" 2>/dev/null | grep -oE 'GLIBC_[0-9.]+' | sort -V | tail -1), syms=$(nm -D "$OUT/$OUTNAME" | grep -c keryx_llama)"
if [ "$VARIANT" = noavx ]; then
  VEX=$(objdump -d --disassemble="ggml_vec_dot_q8_0_q8_0" "$OUT/$OUTNAME" 2>/dev/null | grep -cE '\bv[a-z]' || true)
  echo ">> $OUTNAME VEX-instr count in ggml_vec_dot_q8_0_q8_0 (MUST be 0): $VEX"
  [ "$VEX" = 0 ] || { echo "ERROR: noavx build still contains AVX code"; exit 1; }
fi
