// libkeryx-llama-vk.so — the miner's in-process llama.cpp engine, AMD/Vulkan flavor (zero-dup).
//
// One in-process llama.cpp (Vulkan) instance per loaded model: it OWNS the resident GGUF copy on
// the inference GPU and this wrapper (a) builds a per-tensor prefix/address gather table over the
// SAME VRAM (buffer device addresses via the keryx_vk_* exports appended to ggml-vulkan by the
// build script), (b) runs the PoM possession walk over it (pom_walk_vk.comp — byte-identical math
// to the OpenCL/CUDA kernels), (c) serves a chunk-fetch verifier for the startup byte gate, and
// (d) generates OPoI text. Host-resident tensors (ggml keeps e.g. token_embd on the CPU buffer)
// are supplemented into a small wrapper-owned device buffer so every canonical chunk is
// GPU-reachable; supplement bytes are reported (0 = true zero-dup).
//
// The miner dlopens this next to its own binary; absent = the Vulkan llama-server subprocess and
// candle-CPU fallbacks stay active. Built by hiveos/build-keryx-llama-vk.sh against the SAME
// pinned llama.cpp as the CUDA flavor.
#include "llama.h"
#include "llama-model.h"
#include "ggml.h"
#include "gguf.h"
#include <vulkan/vulkan.h>
#include <algorithm>
#include <cstring>
#include <cstdio>
#include <mutex>
#include <string>
#include <vector>

// SPIR-V blobs, generated by glslc -mfmt=c at build time.
static const uint32_t WALK_SPV[] =
#include "pom_walk_vk.spv.inc"
;
static const uint32_t FETCH_SPV[] =
#include "pom_fetch_vk.spv.inc"
;

// Exports appended to ggml-vulkan.cpp by the build script.
extern "C" bool keryx_vk_raw_handles(size_t dev_num, void ** vk_instance, void ** vk_physical_device,
                                     void ** vk_device, uint32_t * compute_queue_family_index);
extern "C" bool keryx_vk_tensor_addr(const struct ggml_tensor * tensor, uint64_t * gpu_addr, uint64_t * size_bytes);
extern "C" void * keryx_vk_tensor_device(const struct ggml_tensor * tensor);
extern "C" void keryx_vk_queue_submit(size_t dev_num, const void * submit_info, void * fence);

static constexpr uint64_t CHUNK_BYTES = 32;
static constexpr uint32_t NO_WINNER = 0xFFFFFFFFu;

struct PushWalk {
    uint64_t p[4];
    uint64_t t[4];
    uint64_t timestamp;
    uint64_t n_chunks;
    uint64_t start_nonce;
    uint32_t k;
    uint32_t batch;
    uint32_t n_tensors;
    uint32_t pad;
};
struct PushFetch {
    uint64_t first_chunk;
    uint32_t count;
    uint32_t n_tensors;
};

// Chunks per fetch dispatch (out buffer = this * 32 B = 4 MiB): the full-model spike sweeps the
// whole tier through this window; the startup byte gate fetches single chunks.
static constexpr uint32_t FETCH_WINDOW_CHUNKS = 131072;

struct KeryxLlama {
    llama_model*   model = nullptr;
    llama_context* ctx   = nullptr;
    llama_sampler* smpl  = nullptr;
    std::vector<std::string> names; // canonical (byte-lexicographic) order — matches pom.rs
    std::string gguf_path;          // supplements pread their bytes straight from the file
    std::mutex gen_lock;

    // ── zero-dup walk state (all on ggml's own VkDevice) ──
    size_t   gpu = 0;
    VkDevice dev = VK_NULL_HANDLE;
    VkPhysicalDevice phys = VK_NULL_HANDLE;
    uint32_t qfam = 0;
    VkCommandPool cpool = VK_NULL_HANDLE;
    VkCommandBuffer cmd = VK_NULL_HANDLE;
    VkFence fence = VK_NULL_HANDLE;
    VkDescriptorSetLayout dsl = VK_NULL_HANDLE;
    VkDescriptorPool dpool = VK_NULL_HANDLE;
    VkDescriptorSet walk_ds = VK_NULL_HANDLE, fetch_ds = VK_NULL_HANDLE;
    VkPipelineLayout walk_pl = VK_NULL_HANDLE, fetch_pl = VK_NULL_HANDLE;
    VkPipeline walk_pipe = VK_NULL_HANDLE, fetch_pipe = VK_NULL_HANDLE;
    VkShaderModule walk_sm = VK_NULL_HANDLE, fetch_sm = VK_NULL_HANDLE;

    VkBuffer winner_buf = VK_NULL_HANDLE, out32_buf = VK_NULL_HANDLE;
    VkDeviceMemory winner_mem = VK_NULL_HANDLE, out32_mem = VK_NULL_HANDLE;
    void *winner_map = nullptr, *out32_map = nullptr;

    VkBuffer prefix_buf = VK_NULL_HANDLE, addrs_buf = VK_NULL_HANDLE, supl_buf = VK_NULL_HANDLE;
    VkDeviceMemory prefix_mem = VK_NULL_HANDLE, addrs_mem = VK_NULL_HANDLE, supl_mem = VK_NULL_HANDLE;

    uint64_t n_chunks = 0;
    uint32_t n_tensors = 0;
    uint64_t supl_bytes = 0;
    bool walk_ready = false;
    std::mutex walk_lock; // one dispatch at a time on our cmd buffer/fence
};

// ── small Vulkan helpers ────────────────────────────────────────────────────────────────────

static uint32_t find_mem_type(VkPhysicalDevice phys, uint32_t type_bits, VkMemoryPropertyFlags want) {
    VkPhysicalDeviceMemoryProperties mp;
    vkGetPhysicalDeviceMemoryProperties(phys, &mp);
    for (uint32_t i = 0; i < mp.memoryTypeCount; i++) {
        if ((type_bits & (1u << i)) && (mp.memoryTypes[i].propertyFlags & want) == want) {
            return i;
        }
    }
    return UINT32_MAX;
}

// Create a buffer + bound memory. `bda` adds SHADER_DEVICE_ADDRESS usage/alloc flags. `map` (host
// visible+coherent) maps it and returns the pointer via *mapped.
static bool make_buffer(KeryxLlama* h, VkDeviceSize size, VkBufferUsageFlags usage,
                        VkMemoryPropertyFlags props, bool bda, VkBuffer* buf, VkDeviceMemory* mem,
                        void** mapped) {
    VkBufferCreateInfo bi{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};
    bi.size = size;
    bi.usage = usage | (bda ? VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT : 0);
    bi.sharingMode = VK_SHARING_MODE_EXCLUSIVE;
    if (vkCreateBuffer(h->dev, &bi, nullptr, buf) != VK_SUCCESS) return false;
    VkMemoryRequirements req;
    vkGetBufferMemoryRequirements(h->dev, *buf, &req);
    uint32_t mt = find_mem_type(h->phys, req.memoryTypeBits, props);
    if (mt == UINT32_MAX) return false;
    VkMemoryAllocateFlagsInfo fi{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO};
    fi.flags = VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT;
    VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};
    ai.pNext = bda ? &fi : nullptr;
    ai.allocationSize = req.size;
    ai.memoryTypeIndex = mt;
    if (vkAllocateMemory(h->dev, &ai, nullptr, mem) != VK_SUCCESS) return false;
    if (vkBindBufferMemory(h->dev, *buf, *mem, 0) != VK_SUCCESS) return false;
    if (mapped) {
        if (vkMapMemory(h->dev, *mem, 0, VK_WHOLE_SIZE, 0, mapped) != VK_SUCCESS) return false;
    }
    return true;
}

// Submit the recorded h->cmd through ggml's queue-mutex-guarded hook and wait on our fence.
static bool submit_and_wait(KeryxLlama* h) {
    VkSubmitInfo si{VK_STRUCTURE_TYPE_SUBMIT_INFO};
    si.commandBufferCount = 1;
    si.pCommandBuffers = &h->cmd;
    vkResetFences(h->dev, 1, &h->fence);
    keryx_vk_queue_submit(h->gpu, &si, (void*)h->fence);
    return vkWaitForFences(h->dev, 1, &h->fence, VK_TRUE, 30ull * 1000 * 1000 * 1000) == VK_SUCCESS;
}

// Upload `data` into `dst` (device-local) through a bounded host-visible staging window.
static bool staged_upload(KeryxLlama* h, VkBuffer dst, const uint8_t* data, VkDeviceSize size) {
    const VkDeviceSize WINDOW = 64ull << 20;
    VkBuffer stage; VkDeviceMemory stage_mem; void* map = nullptr;
    if (!make_buffer(h, std::min(WINDOW, size), VK_BUFFER_USAGE_TRANSFER_SRC_BIT,
                     VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
                     false, &stage, &stage_mem, &map)) {
        return false;
    }
    bool ok = true;
    for (VkDeviceSize off = 0; off < size && ok; off += WINDOW) {
        VkDeviceSize n = std::min(WINDOW, size - off);
        memcpy(map, data + off, n);
        vkResetCommandBuffer(h->cmd, 0);
        VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
        bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
        vkBeginCommandBuffer(h->cmd, &bi);
        VkBufferCopy c{0, off, n};
        vkCmdCopyBuffer(h->cmd, stage, dst, 1, &c);
        vkEndCommandBuffer(h->cmd);
        ok = submit_and_wait(h);
    }
    vkUnmapMemory(h->dev, stage_mem);
    vkDestroyBuffer(h->dev, stage, nullptr);
    vkFreeMemory(h->dev, stage_mem, nullptr);
    return ok;
}

static VkPipeline make_pipeline(KeryxLlama* h, const uint32_t* spv, size_t spv_bytes,
                                uint32_t push_bytes, VkShaderModule* sm, VkPipelineLayout* pl) {
    VkShaderModuleCreateInfo smi{VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO};
    smi.codeSize = spv_bytes;
    smi.pCode = spv;
    if (vkCreateShaderModule(h->dev, &smi, nullptr, sm) != VK_SUCCESS) return VK_NULL_HANDLE;
    VkPushConstantRange pcr{VK_SHADER_STAGE_COMPUTE_BIT, 0, push_bytes};
    VkPipelineLayoutCreateInfo pli{VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO};
    pli.setLayoutCount = 1;
    pli.pSetLayouts = &h->dsl;
    pli.pushConstantRangeCount = 1;
    pli.pPushConstantRanges = &pcr;
    if (vkCreatePipelineLayout(h->dev, &pli, nullptr, pl) != VK_SUCCESS) return VK_NULL_HANDLE;
    VkComputePipelineCreateInfo cpi{VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO};
    cpi.stage = {VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO, nullptr, 0,
                 VK_SHADER_STAGE_COMPUTE_BIT, *sm, "main", nullptr};
    cpi.layout = *pl;
    VkPipeline pipe = VK_NULL_HANDLE;
    vkCreateComputePipelines(h->dev, VK_NULL_HANDLE, 1, &cpi, nullptr, &pipe);
    return pipe;
}

// ── walk construction: gather table over llama's resident tensors ─────────────────────────────

static bool walk_init(KeryxLlama* h) {
    // ── Canonical reference = the GGUF file's own tensor list (names, on-disk sizes, offsets) —
    // NOT llama's runtime list, which may add tied/converted/padded tensors and would break the
    // pinned chunk count. The chunk layout below is byte-for-byte what pom.rs WeightIndex indexes.
    ggml_context* meta = nullptr;
    gguf_init_params gp = { /*no_alloc*/ true, &meta };
    gguf_context* g = gguf_init_from_file(h->gguf_path.c_str(), gp);
    if (!g) {
        fprintf(stderr, "keryx-llama-vk: gguf meta parse failed\n");
        return false;
    }
    const size_t data_off = gguf_get_data_offset(g);
    std::vector<std::string> gnames;
    for (int64_t i = 0; i < gguf_get_n_tensors(g); i++) gnames.push_back(gguf_get_tensor_name(g, i));
    std::sort(gnames.begin(), gnames.end());

    // ── Self-locate the model's device: main_gpu requests and ggml's device numbering do not
    // always agree, and a BDA is only valid on its owning device. Match the first VK-resident
    // tensor's VkDevice against raw_handles across dev_num.
    VkDevice model_dev = VK_NULL_HANDLE;
    for (auto& name : gnames) {
        const ggml_tensor* t = h->model->get_tensor(name.c_str());
        if (t) {
            if (void* d = keryx_vk_tensor_device(t)) { model_dev = (VkDevice)d; break; }
        }
    }
    if (!model_dev) {
        fprintf(stderr, "keryx-llama-vk: no VK-resident tensor found (model on CPU?)\n");
        gguf_free(g); if (meta) ggml_free(meta);
        return false;
    }
    bool located = false;
    for (size_t dn = 0; dn < 16 && !located; dn++) {
        void *inst, *phys, *dev;
        uint32_t qfam;
        if (!keryx_vk_raw_handles(dn, &inst, &phys, &dev, &qfam)) continue;
        if ((VkDevice)dev == model_dev) {
            h->gpu = dn;
            h->dev = (VkDevice)dev;
            h->phys = (VkPhysicalDevice)phys;
            h->qfam = qfam;
            located = true;
        }
    }
    if (!located) {
        fprintf(stderr, "keryx-llama-vk: could not match the model's VkDevice (no BDA?)\n");
        gguf_free(g); if (meta) ggml_free(meta);
        return false;
    }

    // Command pool + buffer + fence on ggml's compute queue family (submits go through the
    // guarded hook, so we never race ggml's own queue use).
    VkCommandPoolCreateInfo cpi{VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO};
    cpi.flags = VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT;
    cpi.queueFamilyIndex = h->qfam;
    if (vkCreateCommandPool(h->dev, &cpi, nullptr, &h->cpool) != VK_SUCCESS) return false;
    VkCommandBufferAllocateInfo cai{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};
    cai.commandPool = h->cpool;
    cai.level = VK_COMMAND_BUFFER_LEVEL_PRIMARY;
    cai.commandBufferCount = 1;
    if (vkAllocateCommandBuffers(h->dev, &cai, &h->cmd) != VK_SUCCESS) return false;
    VkFenceCreateInfo fci{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};
    if (vkCreateFence(h->dev, &fci, nullptr, &h->fence) != VK_SUCCESS) return false;

    // ── Canonical gather table, keyed off the GGUF list. A tensor rides zero-dup ONLY when
    // llama holds it VK-resident on the model's device at EXACTLY its on-disk byte size (no
    // conversion/padding); everything else is supplemented with bytes pread from the GGUF file
    // itself — byte-identical to the possession index by construction.
    std::vector<uint64_t> prefix{0};
    std::vector<uint64_t> addrs;
    std::vector<std::pair<size_t, uint64_t>> supl_src; // (gguf file offset, chunk bytes) to read
    std::vector<uint64_t> supl_off;                    // per-entry offset in the supplement buffer
    uint64_t supl_total = 0;
    size_t n_resident = 0;
    for (auto& name : gnames) {
        ggml_tensor* mt = ggml_get_tensor(meta, name.c_str());
        int64_t gi = gguf_find_tensor(g, name.c_str());
        if (!mt || gi < 0) continue;
        const uint64_t gguf_nbytes = ggml_nbytes(mt);
        const uint64_t chunks = gguf_nbytes / CHUNK_BYTES;
        if (chunks == 0) continue;
        const ggml_tensor* t = h->model->get_tensor(name.c_str());
        uint64_t addr = 0, sz = 0;
        if (t && keryx_vk_tensor_addr(t, &addr, &sz) && sz == gguf_nbytes
            && keryx_vk_tensor_device(t) == (void*)model_dev) {
            addrs.push_back(addr);
            n_resident++;
        } else {
            supl_src.push_back({data_off + gguf_get_tensor_offset(g, gi), chunks * CHUNK_BYTES});
            supl_off.push_back(supl_total);
            addrs.push_back(0); // patched to supplement BDA + offset below
            supl_total += chunks * CHUNK_BYTES;
        }
        prefix.push_back(prefix.back() + chunks);
    }
    gguf_free(g);
    if (meta) ggml_free(meta);
    h->n_chunks = prefix.back();
    h->n_tensors = (uint32_t)addrs.size();
    h->supl_bytes = supl_total;
    if (h->n_chunks == 0) return false;

    // Supplement buffer (device-local, BDA), filled straight from the GGUF file.
    if (supl_total > 0) {
        if (!make_buffer(h, supl_total, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                         VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, true, &h->supl_buf, &h->supl_mem, nullptr)) {
            return false;
        }
        FILE* f = fopen(h->gguf_path.c_str(), "rb");
        if (!f) return false;
        std::vector<uint8_t> flat(supl_total);
        for (size_t i = 0; i < supl_src.size(); i++) {
            if (fseeko(f, (off_t)supl_src[i].first, SEEK_SET) != 0 ||
                fread(flat.data() + supl_off[i], 1, supl_src[i].second, f) != supl_src[i].second) {
                fclose(f);
                fprintf(stderr, "keryx-llama-vk: supplement read failed\n");
                return false;
            }
        }
        fclose(f);
        if (!staged_upload(h, h->supl_buf, flat.data(), supl_total)) return false;
        VkBufferDeviceAddressInfo dai{VK_STRUCTURE_TYPE_BUFFER_DEVICE_ADDRESS_INFO};
        dai.buffer = h->supl_buf;
        uint64_t supl_bda = vkGetBufferDeviceAddress(h->dev, &dai);
        size_t si = 0;
        for (size_t j = 0; j < addrs.size() && si < supl_src.size(); j++) {
            if (addrs[j] == 0) { addrs[j] = supl_bda + supl_off[si]; si++; }
        }
    }

    // Table + result buffers. The table is hot (binary-searched every gather) -> device-local.
    if (!make_buffer(h, prefix.size() * 8, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                     VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, false, &h->prefix_buf, &h->prefix_mem, nullptr)) return false;
    if (!staged_upload(h, h->prefix_buf, (const uint8_t*)prefix.data(), prefix.size() * 8)) return false;
    if (!make_buffer(h, addrs.size() * 8, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                     VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT, false, &h->addrs_buf, &h->addrs_mem, nullptr)) return false;
    if (!staged_upload(h, h->addrs_buf, (const uint8_t*)addrs.data(), addrs.size() * 8)) return false;
    if (!make_buffer(h, 4, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT | VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                     VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
                     false, &h->winner_buf, &h->winner_mem, &h->winner_map)) return false;
    if (!make_buffer(h, (VkDeviceSize)FETCH_WINDOW_CHUNKS * CHUNK_BYTES, VK_BUFFER_USAGE_STORAGE_BUFFER_BIT,
                     VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT,
                     false, &h->out32_buf, &h->out32_mem, &h->out32_map)) return false;

    // Descriptors: {binding0 result, binding1 prefix, binding2 addrs} — one set per pipeline.
    VkDescriptorSetLayoutBinding b[3]{};
    for (uint32_t i = 0; i < 3; i++) {
        b[i] = {i, VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 1, VK_SHADER_STAGE_COMPUTE_BIT, nullptr};
    }
    VkDescriptorSetLayoutCreateInfo dli{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO};
    dli.bindingCount = 3;
    dli.pBindings = b;
    if (vkCreateDescriptorSetLayout(h->dev, &dli, nullptr, &h->dsl) != VK_SUCCESS) return false;
    VkDescriptorPoolSize ps{VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, 6};
    VkDescriptorPoolCreateInfo dpi{VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO};
    dpi.maxSets = 2;
    dpi.poolSizeCount = 1;
    dpi.pPoolSizes = &ps;
    if (vkCreateDescriptorPool(h->dev, &dpi, nullptr, &h->dpool) != VK_SUCCESS) return false;
    VkDescriptorSetLayout layouts[2] = {h->dsl, h->dsl};
    VkDescriptorSetAllocateInfo dsa{VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO};
    dsa.descriptorPool = h->dpool;
    dsa.descriptorSetCount = 2;
    dsa.pSetLayouts = layouts;
    VkDescriptorSet sets[2];
    if (vkAllocateDescriptorSets(h->dev, &dsa, sets) != VK_SUCCESS) return false;
    h->walk_ds = sets[0];
    h->fetch_ds = sets[1];
    auto write_ds = [&](VkDescriptorSet ds, VkBuffer b0) {
        VkDescriptorBufferInfo bi[3] = {{b0, 0, VK_WHOLE_SIZE}, {h->prefix_buf, 0, VK_WHOLE_SIZE}, {h->addrs_buf, 0, VK_WHOLE_SIZE}};
        VkWriteDescriptorSet w[3]{};
        for (uint32_t i = 0; i < 3; i++) {
            w[i] = {VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET, nullptr, ds, i, 0, 1,
                    VK_DESCRIPTOR_TYPE_STORAGE_BUFFER, nullptr, &bi[i], nullptr};
        }
        vkUpdateDescriptorSets(h->dev, 3, w, 0, nullptr);
    };
    write_ds(h->walk_ds, h->winner_buf);
    write_ds(h->fetch_ds, h->out32_buf);

    h->walk_pipe = make_pipeline(h, WALK_SPV, sizeof(WALK_SPV), sizeof(PushWalk), &h->walk_sm, &h->walk_pl);
    h->fetch_pipe = make_pipeline(h, FETCH_SPV, sizeof(FETCH_SPV), sizeof(PushFetch), &h->fetch_sm, &h->fetch_pl);
    if (!h->walk_pipe || !h->fetch_pipe) return false;

    h->walk_ready = true;
    fprintf(stderr,
            "keryx-llama-vk: zero-dup walk ready on vk device %zu — %u tensors (%zu VRAM-resident, "
            "%zu supplemented), N=%llu chunks, %llu supplement bytes\n",
            h->gpu, h->n_tensors, n_resident, (size_t)h->n_tensors - n_resident,
            (unsigned long long)h->n_chunks, (unsigned long long)supl_total);
    return true;
}

// Record + run one compute dispatch (pipe/ds/push already chosen). Fills `fill_buf` with
// 0xFFFFFFFF words first when given (the winner reset).
static bool run_dispatch(KeryxLlama* h, VkPipeline pipe, VkPipelineLayout pl, VkDescriptorSet ds,
                         const void* push, uint32_t push_bytes, uint32_t groups, VkBuffer fill_buf) {
    vkResetCommandBuffer(h->cmd, 0);
    VkCommandBufferBeginInfo bi{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};
    bi.flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;
    vkBeginCommandBuffer(h->cmd, &bi);
    if (fill_buf) {
        vkCmdFillBuffer(h->cmd, fill_buf, 0, VK_WHOLE_SIZE, NO_WINNER);
        VkMemoryBarrier mb{VK_STRUCTURE_TYPE_MEMORY_BARRIER, nullptr,
                           VK_ACCESS_TRANSFER_WRITE_BIT, VK_ACCESS_SHADER_READ_BIT | VK_ACCESS_SHADER_WRITE_BIT};
        vkCmdPipelineBarrier(h->cmd, VK_PIPELINE_STAGE_TRANSFER_BIT, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
                             0, 1, &mb, 0, nullptr, 0, nullptr);
    }
    vkCmdBindPipeline(h->cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pipe);
    vkCmdBindDescriptorSets(h->cmd, VK_PIPELINE_BIND_POINT_COMPUTE, pl, 0, 1, &ds, 0, nullptr);
    vkCmdPushConstants(h->cmd, pl, VK_SHADER_STAGE_COMPUTE_BIT, 0, push_bytes, push);
    vkCmdDispatch(h->cmd, groups, 1, 1);
    VkMemoryBarrier hb{VK_STRUCTURE_TYPE_MEMORY_BARRIER, nullptr, VK_ACCESS_SHADER_WRITE_BIT, VK_ACCESS_HOST_READ_BIT};
    vkCmdPipelineBarrier(h->cmd, VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT, VK_PIPELINE_STAGE_HOST_BIT,
                         0, 1, &hb, 0, nullptr, 0, nullptr);
    vkEndCommandBuffer(h->cmd);
    return submit_and_wait(h);
}

// ── exported ABI ───────────────────────────────────────────────────────────────────────────────

extern "C" {

// Core ABI (load/generate/free) matches the CUDA flavor; the _vk_abi covers the walk exports.
int keryx_llama_abi() { return 2; }
int keryx_llama_vk_abi() { return 1; }

KeryxLlama* keryx_llama_load(const char* gguf_path, int gpu, int n_ctx) {
    llama_backend_init();
    llama_model_params mp = llama_model_default_params();
    mp.n_gpu_layers = 999;
    mp.split_mode   = LLAMA_SPLIT_MODE_NONE; // ONE GPU — never layer-split across mining cards
    mp.main_gpu     = gpu;
    mp.use_mmap     = true;
    llama_model* model = llama_model_load_from_file(gguf_path, mp);
    if (!model) return nullptr;

    llama_context_params cp = llama_context_default_params();
    cp.n_ctx = n_ctx > 0 ? n_ctx : 4096;
    llama_context* ctx = llama_init_from_model(model, cp);
    if (!ctx) { llama_model_free(model); return nullptr; }

    llama_sampler* smpl = llama_sampler_chain_init(llama_sampler_chain_default_params());
    llama_sampler_chain_add(smpl, llama_sampler_init_top_p(0.9f, 1));
    llama_sampler_chain_add(smpl, llama_sampler_init_temp(0.7f));
    llama_sampler_chain_add(smpl, llama_sampler_init_dist(42));

    auto* h = new KeryxLlama();
    h->model = model; h->ctx = ctx; h->smpl = smpl;
    h->gguf_path = gguf_path;
    for (auto& p : model->tensors_by_name) h->names.push_back(p.first);
    std::sort(h->names.begin(), h->names.end());

    if (!walk_init(h)) {
        // The engine still serves inference without the walk; the miner checks
        // keryx_llama_pom_ready and keeps its own OpenCL blob when false.
        fprintf(stderr, "keryx-llama-vk: walk init failed — inference-only mode\n");
    }
    return h;
}

size_t keryx_llama_tensor_count(KeryxLlama* h) { return h ? h->names.size() : 0; }

// ── zero-dup walk surface ──
bool     keryx_llama_pom_ready(KeryxLlama* h) { return h && h->walk_ready; }
uint64_t keryx_llama_pom_n_chunks(KeryxLlama* h) { return h ? h->n_chunks : 0; }
uint64_t keryx_llama_pom_supl_bytes(KeryxLlama* h) { return h ? h->supl_bytes : 0; }

// Fetch `count` (≤ FETCH_WINDOW_CHUNKS) canonical chunks starting at `first` through the exact
// table+BDA path the walk gathers with. `out` receives count*32 bytes.
bool keryx_llama_pom_fetch_range(KeryxLlama* h, uint64_t first, uint32_t count, uint8_t* out) {
    if (!h || !h->walk_ready || count == 0 || count > FETCH_WINDOW_CHUNKS || first + count > h->n_chunks) {
        return false;
    }
    std::lock_guard<std::mutex> g(h->walk_lock);
    PushFetch pf{first, count, h->n_tensors};
    uint32_t groups = (count + 63) / 64;
    if (!run_dispatch(h, h->fetch_pipe, h->fetch_pl, h->fetch_ds, &pf, sizeof(pf), groups, nullptr)) return false;
    memcpy(out, h->out32_map, (size_t)count * CHUNK_BYTES);
    return true;
}

// Fetch canonical chunk `off` (the miner's startup byte gate).
bool keryx_llama_pom_fetch(KeryxLlama* h, uint64_t off, uint8_t out[32]) {
    return keryx_llama_pom_fetch_range(h, off, 1, out);
}

// Grind ONE dispatch of `batch` nonces from `start_nonce` (the caller sub-batches for TDR safety
// and lowest-nonce early exit, exactly like the OpenCL driver). Returns the lowest winning
// in-dispatch offset, or -1 for none / -2 on dispatch error.
int64_t keryx_llama_pom_mine(KeryxLlama* h, const uint64_t p[4], const uint64_t t[4],
                             uint64_t timestamp, uint64_t start_nonce, uint32_t batch, uint32_t k) {
    if (!h || !h->walk_ready || batch == 0) return -2;
    std::lock_guard<std::mutex> g(h->walk_lock);
    PushWalk pw{};
    memcpy(pw.p, p, 32);
    memcpy(pw.t, t, 32);
    pw.timestamp = timestamp;
    pw.n_chunks = h->n_chunks;
    pw.start_nonce = start_nonce;
    pw.k = k;
    pw.batch = batch;
    pw.n_tensors = h->n_tensors;
    uint32_t groups = (batch + 63) / 64;
    if (!run_dispatch(h, h->walk_pipe, h->walk_pl, h->walk_ds, &pw, sizeof(pw), groups, h->winner_buf)) return -2;
    uint32_t w;
    memcpy(&w, h->winner_map, 4);
    return w == NO_WINNER ? -1 : (int64_t)w;
}

// Generate up to max_tokens; writes UTF-8 into out (cap bytes, NUL-terminated). Returns written
// length, or -1 on error. Serialized — one generation at a time (OPoI challenges are rare).
int keryx_llama_generate(KeryxLlama* h, const char* prompt, int max_tokens, char* out, int cap) {
    if (!h || !prompt || !out || cap < 2) return -1;
    std::lock_guard<std::mutex> g(h->gen_lock);
    const llama_vocab* vocab = llama_model_get_vocab(h->model);

    std::vector<llama_token> toks(strlen(prompt) + 16);
    int n = llama_tokenize(vocab, prompt, (int32_t)strlen(prompt), toks.data(), (int32_t)toks.size(), true, true);
    if (n < 0) return -1;
    toks.resize(n);

    llama_memory_clear(llama_get_memory(h->ctx), true);
    llama_batch batch = llama_batch_get_one(toks.data(), (int32_t)toks.size());
    int written = 0;
    for (int i = 0; i < max_tokens; i++) {
        if (llama_decode(h->ctx, batch) != 0) break;
        llama_token tok = llama_sampler_sample(h->smpl, h->ctx, -1);
        if (llama_vocab_is_eog(vocab, tok)) break;
        char piece[256];
        int pn = llama_token_to_piece(vocab, tok, piece, sizeof(piece), 0, true);
        if (pn < 0) break;
        if (written + pn >= cap - 1) break;
        memcpy(out + written, piece, pn);
        written += pn;
        batch = llama_batch_get_one(&tok, 1);
    }
    out[written] = 0;
    return written;
}

void keryx_llama_free(KeryxLlama* h) {
    if (!h) return;
    if (h->dev) {
        vkDeviceWaitIdle(h->dev);
        auto dbuf = [&](VkBuffer b, VkDeviceMemory m) {
            if (b) vkDestroyBuffer(h->dev, b, nullptr);
            if (m) vkFreeMemory(h->dev, m, nullptr);
        };
        dbuf(h->winner_buf, h->winner_mem);
        dbuf(h->out32_buf, h->out32_mem);
        dbuf(h->prefix_buf, h->prefix_mem);
        dbuf(h->addrs_buf, h->addrs_mem);
        dbuf(h->supl_buf, h->supl_mem);
        if (h->walk_pipe) vkDestroyPipeline(h->dev, h->walk_pipe, nullptr);
        if (h->fetch_pipe) vkDestroyPipeline(h->dev, h->fetch_pipe, nullptr);
        if (h->walk_pl) vkDestroyPipelineLayout(h->dev, h->walk_pl, nullptr);
        if (h->fetch_pl) vkDestroyPipelineLayout(h->dev, h->fetch_pl, nullptr);
        if (h->walk_sm) vkDestroyShaderModule(h->dev, h->walk_sm, nullptr);
        if (h->fetch_sm) vkDestroyShaderModule(h->dev, h->fetch_sm, nullptr);
        if (h->dpool) vkDestroyDescriptorPool(h->dev, h->dpool, nullptr);
        if (h->dsl) vkDestroyDescriptorSetLayout(h->dev, h->dsl, nullptr);
        if (h->fence) vkDestroyFence(h->dev, h->fence, nullptr);
        if (h->cpool) vkDestroyCommandPool(h->dev, h->cpool, nullptr);
    }
    if (h->smpl) llama_sampler_free(h->smpl);
    if (h->ctx) llama_free(h->ctx);
    if (h->model) llama_model_free(h->model);
    delete h;
}

} // extern "C"
