//! AMD GPU inference via a bundled llama.cpp **Vulkan** `llama-server` subprocess.
//!
//! candle 0.9 has no AMD-GPU backend, so on the AMD/`pom-opencl` build the OPoI LLM text is
//! generated by llama.cpp (Vulkan) on the AMD GPU instead of candle on the CPU. We spawn
//! `llama-server` once (the GGUF stays resident in VRAM) and `generate()` HTTP-POSTs `/completion`.
//!
//! This is OPoI-safe: consensus verifies the fixed-point `model_fixed` commitment (computed
//! separately, bit-exact on all hardware) — the Gemma *text* is user-facing utility with no
//! determinism requirement, so a non-candle engine is fine.
//!
//! Best-effort + self-disabling: if the bundled `llama-server` is missing, Vulkan/AMD GPU is
//! unavailable, or the server doesn't come up healthy, `AVAILABLE` stays false and the caller
//! (`slm::load_and_run_inference`) transparently falls back to candle-CPU.

use std::process::{Child, Command, Stdio};
use std::sync::atomic::{AtomicBool, AtomicU16, Ordering};
use std::sync::Mutex;
use std::time::{Duration, Instant};

static SERVER: Mutex<Option<Child>> = Mutex::new(None);
static AVAILABLE: AtomicBool = AtomicBool::new(false);
static PORT: AtomicU16 = AtomicU16::new(0);

/// Whether the Vulkan llama-server is up and ready to serve inference.
pub fn available() -> bool {
    AVAILABLE.load(Ordering::Relaxed)
}

/// Locate the bundled `llama-server` next to our own executable (shipped in the AMD package).
fn server_binary() -> Option<std::path::PathBuf> {
    let exe = std::env::current_exe().ok()?;
    let dir = exe.parent()?;
    let bin = dir.join("llama-server");
    if bin.exists() {
        Some(bin)
    } else {
        None
    }
}

/// Spawn the Vulkan `llama-server` for `gguf_path` and block until it's healthy (or give up).
/// Returns true on success. Idempotent-ish: call once at startup. Any failure → false (CPU fallback).
///
/// Device: defaults to llama.cpp's default Vulkan device, which on a headless AMD mining rig is the
/// AMD GPU. Override with `KERYX_LLAMA_VK_DEVICE` (a `GGML_VK_VISIBLE_DEVICES` value, e.g. "1") on
/// boxes with an integrated GPU to skip.
pub fn try_start(gguf_path: &str, port: u16) -> bool {
    if available() {
        return true;
    }
    let server_bin = match server_binary() {
        Some(b) => b,
        None => {
            log::info!("llama_vulkan: no bundled llama-server next to the binary — OPoI inference stays on CPU.");
            return false;
        }
    };
    if !std::path::Path::new(gguf_path).exists() {
        log::warn!("llama_vulkan: GGUF {gguf_path} not present yet — cannot start GPU inference server.");
        return false;
    }
    let exe_dir = server_bin.parent().map(|p| p.to_path_buf()).unwrap_or_default();
    // The bundled llama-server's ggml/vulkan .so live next to it; libvulkan comes from the system.
    let ld = format!(
        "{}:/usr/lib/x86_64-linux-gnu{}",
        exe_dir.display(),
        std::env::var("LD_LIBRARY_PATH").map(|s| format!(":{s}")).unwrap_or_default()
    );

    let mut cmd = Command::new(&server_bin);
    cmd.args([
        "-m", gguf_path,
        "-ngl", "99", // all layers on the GPU
        "--host", "127.0.0.1",
        "--port", &port.to_string(),
        "-c", "4096",
        "--no-webui",
        "-t", "2", // few CPU threads — the GPU does the work
    ])
    .env("LD_LIBRARY_PATH", ld)
    .stdout(Stdio::null())
    .stderr(Stdio::null());
    if let Ok(dev) = std::env::var("KERYX_LLAMA_VK_DEVICE") {
        cmd.env("GGML_VK_VISIBLE_DEVICES", dev);
    }

    let child = match cmd.spawn() {
        Ok(c) => c,
        Err(e) => {
            log::warn!("llama_vulkan: failed to spawn llama-server ({e}) — falling back to CPU inference.");
            return false;
        }
    };
    *SERVER.lock().unwrap() = Some(child);

    // Poll /health until ready (model load on the GPU can take ~30-60s).
    let health = format!("http://127.0.0.1:{port}/health");
    let deadline = Instant::now() + Duration::from_secs(180);
    log::info!("llama_vulkan: starting Vulkan llama-server on port {port} (loading {gguf_path} into VRAM)…");
    while Instant::now() < deadline {
        // exit early if the child already died
        if let Ok(mut g) = SERVER.lock() {
            if let Some(ch) = g.as_mut() {
                if matches!(ch.try_wait(), Ok(Some(_))) {
                    log::warn!("llama_vulkan: llama-server exited during startup — using CPU inference (no Vulkan/AMD GPU?).");
                    *g = None;
                    return false;
                }
            }
        }
        if ureq::get(&health).timeout(Duration::from_secs(2)).call().is_ok() {
            AVAILABLE.store(true, Ordering::Relaxed);
            PORT.store(port, Ordering::Relaxed);
            log::info!("llama_vulkan: ✓ AMD GPU inference ready (Vulkan llama-server on port {port}).");
            return true;
        }
        std::thread::sleep(Duration::from_secs(2));
    }
    log::warn!("llama_vulkan: llama-server did not become healthy in time — falling back to CPU inference.");
    stop();
    false
}

/// Generate up to `max_tokens` from `prompt` via the running Vulkan llama-server. Returns the
/// completion text, or None on any error (caller falls back to candle-CPU). Temperature/top_p match
/// the candle path (it's user-facing text — exact tokens are not consensus-relevant).
pub fn generate(prompt: &str, max_tokens: usize) -> Option<String> {
    if !available() {
        return None;
    }
    let port = PORT.load(Ordering::Relaxed);
    let url = format!("http://127.0.0.1:{port}/completion");
    let body = serde_json::json!({
        "prompt": prompt,
        "n_predict": max_tokens,
        "temperature": 0.7,
        "top_p": 0.9,
        "cache_prompt": false,
        "stream": false,
    });
    // ureq is built without its `json` feature here, so serialize/parse with serde_json directly.
    let payload = serde_json::to_string(&body).ok()?;
    let resp = match ureq::post(&url)
        .timeout(Duration::from_secs(120))
        .set("Content-Type", "application/json")
        .send_string(&payload)
    {
        Ok(r) => r,
        Err(e) => {
            log::warn!("llama_vulkan: /completion request failed ({e}) — this challenge falls back to CPU.");
            return None;
        }
    };
    let raw = resp.into_string().ok()?;
    let json: serde_json::Value = serde_json::from_str(&raw).ok()?;
    let text = json.get("content")?.as_str()?.to_string();
    if text.is_empty() {
        None
    } else {
        Some(text)
    }
}

/// Kill the llama-server (best-effort). Called on shutdown / failed startup.
pub fn stop() {
    AVAILABLE.store(false, Ordering::Relaxed);
    if let Ok(mut g) = SERVER.lock() {
        if let Some(mut ch) = g.take() {
            let _ = ch.kill();
            let _ = ch.wait();
        }
    }
}
